version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "8000"
    volumes:
      - ./:/usr/src/app
      # - ./gogo/static:/usr/src/app/gogo/static
    command: '/usr/local/bin/gunicorn -w 2 gogo:app --daemon'

  nginx:
    # restart: always
    image: nginx:stable-alpine
    volumes:
      - ./gogo/static:/gogo/static/ # nginx config alias path
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - "8080:80"
