version: '2'
services:
  web:
    build: 
    context: .
    dockerfile: ./dockerfile
    command: '/usr/local/bin/gunicorn -w 2 --daemon'
    volumes:
      - ./gogo/static:/usr/src/app/static
    expose:
      - "8000"

  nginx:
    # restart: always
    image: nginx:stable-alpine
    volumes:
      - ./gogo/static:/gogo/static/ # nginx config alias path
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web:web
    ports:
      - "8080:80"
    depends_on:
      - web
