version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
      # ports:
      # - "8000:8000"
    volumes:
      - ./:/usr/src/app
        # - blog-static:/usr/src/app/gogo/static # nginx config alias path
    command: '/usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 gogo:app'

  nginx:
    # restart: always
    image: nginx:stable-alpine
    volumes:
      # - ./gogo/static:/usr/share/nginx/html # nginx config alias path
      - ./gogo/static:/static # nginx config alias path
      - ./nginx.conf:/etc/nginx/sites-enabled/default.conf
    depends_on:
      - web
    ports:
      - "80:80"
