version: '0.1.3'
services:
  web:
    build: ./dockerfile
    command: '/usr/local/bin/gunicorn -w 2'
    volumes:
      - ./gogo/static:/usr/src/app/static
    ports:
      - "8000:5000"

  nginx:
    # restart: always
    image: nginx:stable-alpine
    ports:
      - "8080:8000"
    volumes:
      - gogo/static:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  gogo/static:
